# Generated by Django 4.2.11 on 2024-03-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_shortsurl_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortsurl',
            name='short_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shortsurl',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
