# Generated by Django 4.2.11 on 2024-03-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shortsurl_short_url_alter_shortsurl_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortsurl',
            name='web_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
