# Generated by Django 4.2.11 on 2024-03-13 19:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shortsurl_web_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortsurl',
            name='url',
            field=models.TextField(unique=True, validators=[core.models.validate_url]),
        ),
    ]
